[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_RUNTIME = "nodejs18.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "bun run dev"
  framework = "next"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
